server {
    listen 8080;
    server_name _;

    location = /health {
        access_log off;
        add_header Content-Type application/json;
        return 200 '{"status":"ok"}';
    }

    location = /api/login {
        proxy_pass http://auth-service:3000/login;
        proxy_set_header Host $host;
    }

    location = /api/orders {
        proxy_pass http://orders-service:3000/orders;
        proxy_set_header Host $host;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
